name: ss2kconfigapp
description: Configures the SmartSpin2k using BLE
version: 1.0.9+29

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <=4.0.0"
  # change this in ci_post_clone.sh as well
  flutter: ">3.20.0 <=3.22.3"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.34.5
  #  git:
  #    url: https://github.com/doudar/flutter-blue-plus.git
  #    path: packages/flutter_blue_plus
  #    ref: v1.0.3
  #dynamic_color: ^1.6.9
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.3.9
  shared_preferences: ^2.2.0
  #flutter_ota: ^0.1.4
  wakelock_plus: ^1.2.8
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  json_theme: ^6.5.4
  flutter_archive: ^6.0.3
  provider: ^6.1.1
  path_provider: ^2.1.5
  xml: ^6.5.0
  # file_picker: ^8.1.7  Doesn't work on Android >14
  # add https://github.com/cypherstack/flutter_file_picker.git:
    # branch: master
  file_picker:
    git:
      url: https://github.com/cypherstack/flutter_file_picker.git
      ref: master
  audioplayers: ^6.1.0
  just_audio: ^0.9.36
  share_plus: ^10.0.0
  fit_tool: ^1.0.5
  gpx: ^2.2.1
  flutter_tts: ^4.2.0
  url_launcher: ^6.2.5
  app_links: ^6.3.2
  reorderables: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.9

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/appainter_theme.json
    - assets/appainter_theme_dark.json
    - assets/sounds/
