// Generated by tool/generate_arcade_story_audio.py. Do not edit.
const arcadeOpeningLines = [
  [
    "Sun is up. Wheels are ready!",
    "Your sunshine fuels MY forge! Ha ha ha!",
    "Help! Follow the sparks!",
    "Hang on, crew. I’m coming!",
  ],
  [
    "One last delivery before sunrise!",
    "Lights out, little couriers! Ha ha ha!",
    "Help! Follow the sparks!",
    "Hang on, crew. I’m coming!",
  ],
  [
    "New wheels! Who wants the first ride?",
    "All your wheels belong to ME! Ha ha ha!",
    "Help! Follow the sparks!",
    "Hang on, crew. I’m coming!",
  ],
  [
    "The seedlight is awake. Let’s grow a new trail!",
    "My roots will swallow every trail! Ha ha ha!",
    "Help! Follow the glowing seeds!",
    "Hang on, Pathfinders. We’ll clear this trail!",
  ],
  [
    "Warm hands, full bottles. Ready for the pass!",
    "Your precious hearth is MINE. Let winter win!",
    "Help! Don’t let our hearth go cold!",
    "Hang on, Rangers. I’ll bring the warmth back!",
  ],
  [
    "Starwheel charged. The midnight relay is on!",
    "The last star belongs to the void! Ha ha ha!",
    "Help! Follow the starlight!",
    "Hang on, Messengers. This relay isn’t over!",
  ],
];
const arcadeEndingGreeting = "Look! Our rider is back!";
const arcadeEndingRelief = [
  "Everyone okay? Let’s get you home.",
  "We made it. Stay together, crew.",
];
const arcadeEndingCheer = [
  "You did it! Three cheers for our hero!",
  "You did it! Three cheers for our hero!",
  "You did it! Three cheers for our hero!",
  "Home at last! Our next trail gets your name!",
  "Everyone’s home! Hot cocoa for our hero!",
  "Crew accounted for! The relay rides again!",
];
const arcadeEndingTogether = "Together all the way! Woo-hoo!";
const arcadeEndingSignoff = [
  "Best crew ever. Now… snacks?",
  "Best crew ever. Now… snacks?",
  "Best crew ever. Now… snacks?",
  "Best crew ever. Save me a picnic spot!",
  "Best crew ever. Make mine extra marshmallows.",
  "Best crew ever. Next delivery: midnight snacks!",
];
const arcadeOpeningChapterMs = [4000, 4000, 4000, 4000];
const arcadeEndingChapterMs = [3400, 3400, 3400, 3400];
