#!/bin/sh
# Run before opening Xcode or starting a Flutter/Xcode build.
set -eu

SCRIPT_DIRECTORY=$(dirname -- "$0")
REPOSITORY_ROOT=$(CDPATH= cd -- "$SCRIPT_DIRECTORY/.." && pwd)
umask 077

if [ -z "${APPLE_TEAM_ID:-}" ]; then
    # Clear any previous team's overrides when switching to unsigned test builds.
    printf '%s\n' '// No Apple team configured. Using unsigned test builds.' \
        > "$REPOSITORY_ROOT/AppleSigning.local.xcconfig"
    echo "APPLE_TEAM_ID is unset; using unsigned test builds."
    exit 0
fi

# Reject malformed values before writing an Xcode build configuration.
case "$APPLE_TEAM_ID" in
    *[!A-Z0-9]*)
        echo "APPLE_TEAM_ID must contain exactly 10 uppercase letters or digits." >&2
        exit 1
        ;;
esac
if [ "${#APPLE_TEAM_ID}" -ne 10 ]; then
    echo "APPLE_TEAM_ID must contain exactly 10 uppercase letters or digits." >&2
    exit 1
fi

cat > "$REPOSITORY_ROOT/AppleSigning.local.xcconfig" <<EOF
// Generated by tool/configure_apple_signing.sh. Do not commit.
DEVELOPMENT_TEAM = $APPLE_TEAM_ID
CODE_SIGNING_ALLOWED = YES
CODE_SIGNING_REQUIRED = YES
EOF
echo "Apple signing configuration is ready for iOS and macOS."
